<?php

/**
 * All Rector rules applied across the BTA projects with their first occurrence
 * Key: Full Rector rule class name
 * Value: Project where the rule was first encountered
 */
return [
    'RectorLaravel\\Rector\\Class_\\AddExtendsAnnotationToModelFactoriesRector' => 'product',
    'Rector\\Transform\\Rector\\FuncCall\\FuncCallToNewRector' => 'product',
    'RectorLaravel\\Rector\\StaticCall\\EloquentMagicMethodToQueryBuilderRector' => 'product',
    'RectorLaravel\\Rector\\PropertyFetch\\ReplaceFakerInstanceWithHelperRector' => 'product',
    'RectorLaravel\\Rector\\Namespace_\\FactoryDefinitionRector' => 'product',
    'RectorLaravel\\Rector\\MethodCall\\UnaliasCollectionMethodsRector' => 'product',
    'RectorLaravel\\Rector\\MethodCall\\ContainerBindConcreteWithClosureOnlyRector' => 'product',
    'RectorLaravel\\Rector\\MethodCall\\AvoidNegatedCollectionFilterOrRejectRector' => 'product',
    'RectorLaravel\\Rector\\If_\\ThrowIfRector' => 'product',
    'RectorLaravel\\Rector\\FuncCall\\HelperFuncCallToFacadeClassRector' => 'product',
    'RectorLaravel\\Rector\\Coalesce\\ApplyDefaultInsteadOfNullCoalesceRector' => 'product',
    'Rector\\CodeQuality\\Rector\\Identical\\SimplifyBoolIdenticalTrueRector' => 'product',
    'Rector\\EarlyReturn\\Rector\\If_\\ChangeOrIfContinueToMultiContinueRector' => 'product',
    'Rector\\Strict\\Rector\\Empty_\\DisallowedEmptyRuleFixerRector' => 'product',
    'Rector\\Php74\\Rector\\Closure\\ClosureToArrowFunctionRector' => 'product',
    'Rector\\CodeQuality\\Rector\\FunctionLike\\SimplifyUselessVariableRector' => 'product',
    'Rector\\CodeQuality\\Rector\\If_\\CombineIfRector' => 'product',
    'Rector\\CodeQuality\\Rector\\If_\\SimplifyIfReturnBoolRector' => 'product',
    'Rector\\PHPUnit\\CodeQuality\\Rector\\MethodCall\\AssertFalseStrposToContainsRector' => 'product',
    'Rector\\PHPUnit\\CodeQuality\\Rector\\MethodCall\\AssertEqualsToSameRector' => 'product',
    'Rector\\PHPUnit\\CodeQuality\\Rector\\Class_\\PreferPHPUnitThisCallRector' => 'product',
    'Rector\\PHPUnit\\CodeQuality\\Rector\\Class_\\NarrowUnusedSetUpDefinedPropertyRector' => 'product',
    'Rector\\Privatization\\Rector\\Class_\\FinalizeTestCaseClassRector' => 'product',
    'Rector\\CodingStyle\\Rector\\PostInc\\PostIncDecToPreIncDecRector' => 'product',
    'Rector\\Carbon\\Rector\\FuncCall\\DateFuncCallToCarbonRector' => 'product',
    'Rector\\EarlyReturn\\Rector\\StmtsAwareInterface\\ReturnEarlyIfVariableRector' => 'product',
    'Rector\\EarlyReturn\\Rector\\Return_\\PreparedValueToEarlyReturnRector' => 'product',
    'Rector\\EarlyReturn\\Rector\\If_\\ChangeIfElseValueAssignToEarlyReturnRector' => 'product',
    'Rector\\Instanceof_\\Rector\\Ternary\\FlipNegatedTernaryInstanceofRector' => 'product',
    'Rector\\Naming\\Rector\\Foreach_\\RenameForeachValueVariableToMatchMethodCallReturnTypeRector' => 'product',
    'Rector\\Naming\\Rector\\Foreach_\\RenameForeachValueVariableToMatchExprVariableRector' => 'product',
    'Rector\\Naming\\Rector\\Class_\\RenamePropertyToMatchTypeRector' => 'product',
    'Rector\\Naming\\Rector\\ClassMethod\\RenameVariableToMatchNewTypeRector' => 'product',
    'Rector\\Naming\\Rector\\ClassMethod\\RenameParamToMatchTypeRector' => 'product',
    'Rector\\Naming\\Rector\\Assign\\RenameVariableToMatchMethodCallReturnTypeRector' => 'product',
    'Rector\\TypeDeclaration\\Rector\\Empty_\\EmptyOnNullableObjectToInstanceOfRector' => 'product',
    'Rector\\TypeDeclaration\\Rector\\Closure\\ClosureReturnTypeRector' => 'product',
    'Rector\\TypeDeclaration\\Rector\\ClassMethod\\StrictArrayParamDimFetchRector' => 'product',
    'Rector\\TypeDeclaration\\Rector\\ClassMethod\\ReturnTypeFromStrictTypedCallRector' => 'product',
    'Rector\\TypeDeclaration\\Rector\\ArrowFunction\\AddArrowFunctionReturnTypeRector' => 'product',
    'Rector\\CodeQuality\\Rector\\Ternary\\UnnecessaryTernaryExpressionRector' => 'product',
    'Rector\\CodeQuality\\Rector\\Ternary\\SwitchNegatedTernaryRector' => 'product',
    'Rector\\CodeQuality\\Rector\\Ternary\\NumberCompareToMaxFuncCallRector' => 'product',
    'Rector\\CodeQuality\\Rector\\Isset_\\IssetOnPropertyObjectToPropertyExistsRector' => 'product',
    'Rector\\CodeQuality\\Rector\\If_\\SimplifyIfElseToTernaryRector' => 'product',
    'Rector\\CodeQuality\\Rector\\If_\\ShortenElseIfRector' => 'product',
    'Rector\\CodeQuality\\Rector\\Identical\\SimplifyConditionsRector' => 'product',
    'Rector\\CodeQuality\\Rector\\Identical\\FlipTypeControlToUseExclusiveTypeRector' => 'product',
    'Rector\\CodeQuality\\Rector\\Empty_\\SimplifyEmptyCheckOnEmptyArrayRector' => 'product',
    'Rector\\CodeQuality\\Rector\\Class_\\InlineConstructorDefaultToPropertyRector' => 'product',
    'Rector\\CodeQuality\\Rector\\BooleanNot\\SimplifyDeMorganBinaryRector' => 'product',
    'Rector\\CodeQuality\\Rector\\Assign\\CombinedAssignRector' => 'product',
    'Rector\\DeadCode\\Rector\\Property\\RemoveUselessVarTagRector' => 'product',
    'Rector\\DeadCode\\Rector\\Assign\\RemoveUnusedVariableAssignRector' => 'product',
    'Rector\\Php80\\Rector\\ClassConstFetch\\ClassOnThisVariableObjectRector' => 'product',
    'Rector\\Php83\\Rector\\ClassMethod\\AddOverrideAttributeToOverriddenMethodsRector' => 'product',
    'Rector\\Php83\\Rector\\ClassConst\\AddTypeToConstRector' => 'product',
    'Rector\\Php81\\Rector\\Property\\ReadOnlyPropertyRector' => 'product',
    'Rector\\Php81\\Rector\\FuncCall\\NullToStrictStringFuncCallArgRector' => 'product',
    'Rector\\Php80\\Rector\\Switch_\\ChangeSwitchToMatchRector' => 'product',
    'Rector\\Php80\\Rector\\NotIdentical\\StrContainsRector' => 'product',
    'Rector\\Php80\\Rector\\Identical\\StrStartsWithRector' => 'product',
    'Rector\\Php80\\Rector\\FuncCall\\ClassOnObjectRector' => 'product',
    'Rector\\Php80\\Rector\\Class_\\ClassPropertyAssignToConstructorPromotionRector' => 'product',
    'Rector\\Php70\\Rector\\Ternary\\TernaryToNullCoalescingRector' => 'product',
    'Rector\\Php74\\Rector\\Property\\RestoreDefaultNullToNullableTypePropertyRector' => 'agreements',
    'RectorLaravel\\Rector\\MethodCall\\ReplaceServiceContainerCallArgRector' => 'agreements',
    'Rector\\Arguments\\Rector\\ClassMethod\\ArgumentAdderRector' => 'checkout',
    'Rector\\Php72\\Rector\\FuncCall\\GetClassOnNullRector' => 'checkout',
    'Rector\\Php80\\Rector\\Catch_\\RemoveUnusedVariableInCatchRector' => 'checkout',
    'Rector\\Php82\\Rector\\Class_\\ReadOnlyClassRector' => 'checkout',
    'Rector\\DeadCode\\Rector\\ClassMethod\\RemoveUselessParamTagRector' => 'checkout',
    'Rector\\TypeDeclaration\\Rector\\ClassMethod\\AddMethodCallBasedStrictParamTypeRector' => 'checkout',
    'Rector\\TypeDeclaration\\Rector\\ClassMethod\\AddParamTypeFromPropertyTypeRector' => 'checkout',
    'Rector\\TypeDeclaration\\Rector\\ClassMethod\\ParamTypeByMethodCallTypeRector' => 'checkout',
    'Rector\\TypeDeclaration\\Rector\\ClassMethod\\ParamTypeByParentCallTypeRector' => 'checkout',
    'Rector\\TypeDeclaration\\Rector\\ClassMethod\\ReturnNullableTypeRector' => 'checkout',
    'Rector\\TypeDeclaration\\Rector\\Property\\TypedPropertyFromStrictConstructorRector' => 'checkout',
    'Rector\\PHPUnit\\CodeQuality\\Rector\\ClassMethod\\AddInstanceofAssertForNullableInstanceRector' => 'checkout',
    'Rector\\PHPUnit\\CodeQuality\\Rector\\MethodCall\\AssertCompareOnCountableWithMethodToAssertCountRector' => 'checkout',
    'Rector\\PHPUnit\\CodeQuality\\Rector\\MethodCall\\AssertEmptyNullableObjectToAssertInstanceofRector' => 'checkout',
    'Rector\\PHPUnit\\CodeQuality\\Rector\\MethodCall\\AssertEqualsOrAssertSameFloatParameterToSpecificMethodsTypeRector' => 'checkout',
    'Rector\\PHPUnit\\CodeQuality\\Rector\\MethodCall\\AssertInstanceOfComparisonRector' => 'checkout',
    'Rector\\CodeQuality\\Rector\\ClassMethod\\LocallyCalledStaticMethodToNonStaticRector' => 'checkout',
    'Rector\\CodeQuality\\Rector\\Foreach_\\UnusedForeachValueToArrayKeysRector' => 'checkout',
    'RectorLaravel\\Rector\\ClassMethod\\MigrateToSimplifiedAttributeRector' => 'checkout',
    'RectorLaravel\\Rector\\Class_\\ModelCastsPropertyToCastsMethodRector' => 'checkout',
    'Rector\\Renaming\\Rector\\PropertyFetch\\RenamePropertyRector' => 'checkout',
    'Rector\\DeadCode\\Rector\\ClassMethod\\RemoveUselessReturnTagRector' => 'checkout',
];
